[workspace]
members = [
  ".",
  "aoc_helper"
]

[workspace.package]
edition = "2021"

[package]
name = "aoc"
version = "0.0.0"
edition = "2021"

[dependencies]
aoc_helper.path = "aoc_helper"
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "day06"
harness = false
